---
AWSTemplateFormatVersion: '2010-09-09'
Description: campaign-central dynamo DB tables

Parameters:
  Stage:
    Description: Environment name
    Type: String
    AllowedValues:
    - PROD
    - DEV

Resources:
  CampaignDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - campaigns
    DeletionPolicy: Retain

  CampaignContentDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: campaignId
        AttributeType: S
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: campaignId
        KeyType: HASH
      - AttributeName: id
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - campaign-content
    DeletionPolicy: Retain

  CampaignUniquesDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: campaignId
        AttributeType: S
      - AttributeName: reportExecutionTimestamp
        AttributeType: S
      KeySchema:
      - AttributeName: campaignId
        KeyType: HASH
      - AttributeName: reportExecutionTimestamp
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - campaign-uniques
    DeletionPolicy: Retain

  CampaignPageViewsDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: campaignId
        AttributeType: S
      - AttributeName: reportExecutionTimestamp
        AttributeType: S
      KeySchema:
      - AttributeName: campaignId
        KeyType: HASH
      - AttributeName: reportExecutionTimestamp
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - campaign-page-views
    DeletionPolicy: Retain

  CampaignReferralsDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: campaignId
        AttributeType: S
      - AttributeName: hash
        AttributeType: S
      KeySchema:
      - AttributeName: campaignId
        KeyType: HASH
      - AttributeName: hash
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - referrals
    DeletionPolicy: Retain

  CampaignLocationAnalyticsLatestDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: territory
        AttributeType: S
      - AttributeName: campaignId
        AttributeType: S
      KeySchema:
      - AttributeName: territory
        KeyType: HASH
      - AttributeName: campaignId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - location
          - analytics
          - latest
    DeletionPolicy: Retain

  CampaignMediaDBTable:
    Type: AWS::DynamoDB::Table
    DependsOn: CampaignAnalyticsLatestDBTable
    Properties:
      AttributeDefinitions:
      - AttributeName: campaignId
        AttributeType: S
      KeySchema:
      - AttributeName: campaignId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - media
    DeletionPolicy: Retain
