---
AWSTemplateFormatVersion: '2010-09-09'
Description: campaign-central dynamo DB tables

Parameters:
  Stage:
    Description: Environment name
    Type: String
    AllowedValues:
    - PROD
    - DEV

Resources:
  CampaignDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - campaigns

  CampaignNotesDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: campaignId
        AttributeType: S
      - AttributeName: created
        AttributeType: N
      KeySchema:
      - AttributeName: campaignId
        KeyType: HASH
      - AttributeName: created
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - campaign-notes

  CampaignContentDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: campaignId
        AttributeType: S
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: campaignId
        KeyType: HASH
      - AttributeName: id
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - campaign-content

  ClientDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - clients

  CampaignAnalyticsDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: key
        AttributeType: S
      - AttributeName: dataType
        AttributeType: S
      KeySchema:
      - AttributeName: key
        KeyType: HASH
      - AttributeName: dataType
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - analytics

  CampaignUniquesDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: campaignId
        AttributeType: S
      - AttributeName: reportExecutionTimestamp
        AttributeType: S
      KeySchema:
      - AttributeName: campaignId
        KeyType: HASH
      - AttributeName: reportExecutionTimestamp
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - campaign-uniques

  CampaignPageViewsDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: campaignId
        AttributeType: S
      - AttributeName: reportExecutionTimestamp
        AttributeType: S
      KeySchema:
      - AttributeName: campaignId
        KeyType: HASH
      - AttributeName: reportExecutionTimestamp
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '10'
        WriteCapacityUnits: '10'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - campaign-page-views

  CampaignReferralsDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: campaignId
        AttributeType: S
      - AttributeName: hash
        AttributeType: S
      KeySchema:
      - AttributeName: campaignId
        KeyType: HASH
      - AttributeName: hash
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - referrals

  CampaignReferralsV2DBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: campaignId
        AttributeType: S
      - AttributeName: hash
        AttributeType: S
      KeySchema:
      - AttributeName: campaignId
        KeyType: HASH
      - AttributeName: hash
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - referralsv2

  CampaignAnalyticsLatestDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: campaignId
        AttributeType: S
      KeySchema:
      - AttributeName: campaignId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - analytics
          - latest

  CampaignMediaDBTable:
    Type: AWS::DynamoDB::Table
    DependsOn: CampaignAnalyticsLatestDBTable
    Properties:
      AttributeDefinitions:
      - AttributeName: campaignId
        AttributeType: S
      KeySchema:
      - AttributeName: campaignId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName:
        Fn::Join:
        - "-"
        - - campaign-central
          - Ref: Stage
          - media
